"use client";

import { useState } from "react";
import { generateAppealDraftFallback } from "@/lib/ai";

export function AppealForm() {
  const [reason, setReason] = useState("No response received");
  const [text, setText] = useState(() => generateAppealDraftFallback("DEMO/R/E/26/00422", "No response has been received within the expected period."));
  return <form className="mt-6 space-y-5"><section className="service-panel p-5"><h2 className="font-bold text-[#123B52]">Original RTI</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-600">Registration number</dt><dd className="font-mono font-semibold">DEMO/R/E/26/00422</dd></div><div><dt className="text-slate-600">Authority</dt><dd className="font-semibold">Demo School Education Authority</dd></div><div><dt className="text-slate-600">Date filed</dt><dd>20 Jul 2026</dd></div><div><dt className="text-slate-600">Fee</dt><dd className="font-semibold">₹0</dd></div></dl></section><section className="service-panel p-5"><label className="block text-sm font-bold text-[#123B52]" htmlFor="appeal-reason">Reason for appeal <span className="text-red-700">*</span></label><select id="appeal-reason" value={reason} onChange={(event) => setReason(event.target.value)} className="mt-2 min-h-11 w-full rounded border border-slate-400 bg-white px-3"><option>No response received</option><option>Response was incomplete</option><option>Response did not address my question</option><option>Other</option></select><label className="mt-5 block text-sm font-bold text-[#123B52]" htmlFor="appeal-text">Appeal text <span className="text-red-700">*</span></label><p className="mt-1 text-xs text-slate-600">Suggested wording is assistance only. You can edit it.</p><textarea id="appeal-text" value={text} onChange={(event) => setText(event.target.value)} maxLength={3000} rows={8} className="field mt-2" /><p className="mt-2 text-right text-xs text-slate-600">{text.length}/3,000 characters</p></section><section className="service-panel p-5"><label className="block text-sm font-bold text-[#123B52]" htmlFor="appeal-document">Supporting document (optional)</label><input id="appeal-document" type="file" accept="application/pdf" className="mt-2 block text-sm" /><p className="mt-2 text-xs text-slate-600">PDF only. Do not upload real personal or financial documents in this demo.</p></section><button type="button" className="rounded bg-moss px-5 py-3 text-sm font-bold text-white">Review First Appeal</button></form>;
}
