"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { decomposeQuestion } from "@/lib/intelligence";

export function QuestionDecomposition({ initialQuestion = "How much money was spent repairing roads in Pune in 2025, which contractors received the work, and how many projects were completed?" }: { initialQuestion?: string }) {
  const [question, setQuestion] = useState(initialQuestion); const [confirmed, setConfirmed] = useState(false);
  const result = useMemo(() => decomposeQuestion(question), [question]);
  return <div className="mt-6"><textarea aria-label="Question to decompose" value={question} onChange={(event) => { setQuestion(event.target.value); setConfirmed(false); }} rows={4} className="field" /><section className="service-panel mt-5 p-5"><p className="text-xs font-bold uppercase tracking-wide text-[#075985]">Question decomposition</p><h2 className="mt-2 text-xl font-bold text-[#123B52]">Your question contains {result.requests.length} information request{result.requests.length === 1 ? "" : "s"}.</h2><div className="mt-4 divide-y divide-slate-200 border border-slate-300">{result.requests.map((request, index) => <div className="flex gap-3 p-4" key={`${request.label}-${index}`}><span className="font-mono text-sm font-bold text-[#075985]">{String(index + 1).padStart(2, "0")}</span><div><p className="font-bold text-[#123B52]">{request.label}</p><p className="mt-1 text-sm text-slate-700">{request.text}</p><p className="mt-1 text-xs text-slate-600">Information type: {request.informationType}</p></div></div>)}</div>{result.hasDifferentOwners && <p className="mt-4 border-l-4 border-[#C65D11] bg-[#FFF7ED] p-3 text-sm text-slate-700">These requests may involve different information owners. Review the grouping before continuing.</p>}<p className="mt-4 text-xs text-slate-600">This is a drafting aid. It does not automatically create multiple RTIs.</p><div className="mt-5 flex flex-wrap gap-3"><Link href={`/readiness?question=${encodeURIComponent(question)}`} onClick={() => setConfirmed(true)} className="rounded bg-moss px-4 py-2 text-sm font-bold text-white">Review and continue</Link><Link href={`/knowledge?query=${encodeURIComponent(question)}`} className="px-4 py-2 text-sm font-bold text-[#075985] underline underline-offset-4">See similar examples</Link></div>{confirmed && <p className="mt-3 text-sm text-green-800">Grouping saved for this demo journey.</p>}</section></div>;
}
