import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { createClient } from "@/lib/server";

const applications = [
  ["Road repair expenditure — Pune", "DEMO/R/E/26/00421", "UNDER REVIEW", "The department is reviewing your request.", "No action needed.", "/rtis/demo-road-pune", "info"],
  ["Government school infrastructure — Nashik", "DEMO/R/E/26/00422", "RESPONSE OVERDUE", "We have not received a response within the expected period.", "Check appeal options.", "/rtis/demo-school-nashik", "warning"],
  ["Public hospital equipment procurement — Mumbai", "DEMO/R/E/26/00423", "RESPONSE RECEIVED", "A response has been issued.", "View response.", "/rtis/demo-hospital-mumbai", "success"],
] as const;

export default async function DashboardPage() {
  const supabase = await createClient();
  const { data: user } = await supabase.auth.getUser();
  const { data } = user.user ? await supabase.from("rti_applications").select("id,title,registration_number,status").order("created_at", { ascending: false }) : { data: null };
  const records = data?.length ? data.map((item) => [item.title, item.registration_number, String(item.status).replaceAll("_", " "), "Your application status is updated.", "View the case record.", `/rtis/${item.id}`, "info"] as const) : applications;
  return <main className="min-h-screen bg-portal-bg"><SiteHeader /><div className="portal-container grid gap-10 py-14 lg:grid-cols-[18rem_minmax(0,1fr)] lg:py-16"><aside><div className="grid h-16 w-16 place-items-center rounded-full bg-slate-200 text-4xl text-slate-700" aria-hidden="true">N</div><nav className="mt-8 space-y-2" aria-label="Account navigation"><Link href="/dashboard" className="block rounded bg-portal-primary px-5 py-3 font-bold text-white">My RTIs</Link><Link href="/appeal" className="block rounded px-5 py-3 text-lg text-slate-700 hover:bg-white">First Appeal</Link><Link href="/second-appeal" className="block rounded px-5 py-3 text-lg text-slate-700 hover:bg-white">Second Appeal</Link><Link href="/authorities" className="block rounded px-5 py-3 text-lg text-slate-700 hover:bg-white">Public Authorities</Link><Link href="/knowledge" className="block rounded px-5 py-3 text-lg text-slate-700 hover:bg-white">Knowledge Library</Link><Link href="/faq" className="block rounded px-5 py-3 text-lg text-slate-700 hover:bg-white">FAQ</Link><Link href="/contact" className="block rounded px-5 py-3 text-lg text-slate-700 hover:bg-white">Contact</Link></nav></aside><section><p className="text-lg text-slate-700">{user.user ? "Signed-in citizen" : "Demo Citizen"}</p><h1 className="mt-2 text-5xl font-bold tracking-tight text-portal-navy">My RTIs</h1><p className="mt-3 text-xl text-slate-700">{records.length} applications</p><div className="mt-10 space-y-6">{records.map(([title, number, status, meaning, action, href, tone]) => <article className="portal-card p-6 sm:p-8" key={number}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="text-2xl font-medium leading-tight text-slate-950">{title}</h2><p className="mt-2 font-mono text-sm font-semibold text-slate-500">{number}</p></div><span className={`status-pill status-pill-${tone}`}>{status}</span></div><div className="mt-6 grid gap-5 border-t border-portal-border pt-5 text-base leading-7 sm:grid-cols-2"><p><strong>What this means:</strong> {meaning}</p><p><strong>Your next action:</strong> {action}</p></div><Link href={href} className="mt-7 inline-block text-lg font-medium text-portal-blue underline decoration-1 underline-offset-4">View details →</Link></article>)}</div></section></div><footer className="portal-footer mt-10"><div className="portal-container flex flex-col gap-5 py-10 sm:flex-row sm:items-center sm:justify-between"><p className="text-3xl font-bold text-portal-navy">RTI Portal</p><nav className="flex flex-wrap gap-x-8 gap-y-3 text-sm text-slate-700"><Link href="/contact">Contact Us</Link><Link href="/help">Accessibility Statement</Link><Link href="/faq">Privacy Policy</Link><span>© 2024 Right to Information. Government of India.</span></nav></div></footer></main>;
}
